/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.sys;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.jooq.util.crate.sys.tables.Checks;
import org.jooq.util.crate.sys.tables.Cluster;
import org.jooq.util.crate.sys.tables.Jobs;
import org.jooq.util.crate.sys.tables.JobsLog;
import org.jooq.util.crate.sys.tables.Nodes;
import org.jooq.util.crate.sys.tables.Operations;
import org.jooq.util.crate.sys.tables.OperationsLog;
import org.jooq.util.crate.sys.tables.Repositories;
import org.jooq.util.crate.sys.tables.Shards;
import org.jooq.util.crate.sys.tables.Snapshots;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sys extends SchemaImpl {

    private static final long serialVersionUID = 621996568;

    /**
     * The reference instance of <code>sys</code>
     */
    public static final Sys SYS = new Sys();

    /**
     * The table <code>sys.checks</code>.
     */
    public final Checks CHECKS = org.jooq.util.crate.sys.tables.Checks.CHECKS;

    /**
     * The table <code>sys.cluster</code>.
     */
    public final Cluster CLUSTER = org.jooq.util.crate.sys.tables.Cluster.CLUSTER;

    /**
     * The table <code>sys.jobs</code>.
     */
    public final Jobs JOBS = org.jooq.util.crate.sys.tables.Jobs.JOBS;

    /**
     * The table <code>sys.jobs_log</code>.
     */
    public final JobsLog JOBS_LOG = org.jooq.util.crate.sys.tables.JobsLog.JOBS_LOG;

    /**
     * The table <code>sys.nodes</code>.
     */
    public final Nodes NODES = org.jooq.util.crate.sys.tables.Nodes.NODES;

    /**
     * The table <code>sys.operations</code>.
     */
    public final Operations OPERATIONS = org.jooq.util.crate.sys.tables.Operations.OPERATIONS;

    /**
     * The table <code>sys.operations_log</code>.
     */
    public final OperationsLog OPERATIONS_LOG = org.jooq.util.crate.sys.tables.OperationsLog.OPERATIONS_LOG;

    /**
     * The table <code>sys.repositories</code>.
     */
    public final Repositories REPOSITORIES = org.jooq.util.crate.sys.tables.Repositories.REPOSITORIES;

    /**
     * The table <code>sys.shards</code>.
     */
    public final Shards SHARDS = org.jooq.util.crate.sys.tables.Shards.SHARDS;

    /**
     * The table <code>sys.snapshots</code>.
     */
    public final Snapshots SNAPSHOTS = org.jooq.util.crate.sys.tables.Snapshots.SNAPSHOTS;

    /**
     * No further instances allowed
     */
    private Sys() {
        super("sys", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Checks.CHECKS,
            Cluster.CLUSTER,
            Jobs.JOBS,
            JobsLog.JOBS_LOG,
            Nodes.NODES,
            Operations.OPERATIONS,
            OperationsLog.OPERATIONS_LOG,
            Repositories.REPOSITORIES,
            Shards.SHARDS,
            Snapshots.SNAPSHOTS);
    }
}
