/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.sys;


import javax.annotation.Generated;

import org.jooq.util.crate.sys.tables.Checks;
import org.jooq.util.crate.sys.tables.Cluster;
import org.jooq.util.crate.sys.tables.Jobs;
import org.jooq.util.crate.sys.tables.JobsLog;
import org.jooq.util.crate.sys.tables.Nodes;
import org.jooq.util.crate.sys.tables.Operations;
import org.jooq.util.crate.sys.tables.OperationsLog;
import org.jooq.util.crate.sys.tables.Repositories;
import org.jooq.util.crate.sys.tables.Shards;
import org.jooq.util.crate.sys.tables.Snapshots;


/**
 * Convenience access to all tables in sys
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sys.checks</code>.
     */
    public static final Checks CHECKS = org.jooq.util.crate.sys.tables.Checks.CHECKS;

    /**
     * The table <code>sys.cluster</code>.
     */
    public static final Cluster CLUSTER = org.jooq.util.crate.sys.tables.Cluster.CLUSTER;

    /**
     * The table <code>sys.jobs</code>.
     */
    public static final Jobs JOBS = org.jooq.util.crate.sys.tables.Jobs.JOBS;

    /**
     * The table <code>sys.jobs_log</code>.
     */
    public static final JobsLog JOBS_LOG = org.jooq.util.crate.sys.tables.JobsLog.JOBS_LOG;

    /**
     * The table <code>sys.nodes</code>.
     */
    public static final Nodes NODES = org.jooq.util.crate.sys.tables.Nodes.NODES;

    /**
     * The table <code>sys.operations</code>.
     */
    public static final Operations OPERATIONS = org.jooq.util.crate.sys.tables.Operations.OPERATIONS;

    /**
     * The table <code>sys.operations_log</code>.
     */
    public static final OperationsLog OPERATIONS_LOG = org.jooq.util.crate.sys.tables.OperationsLog.OPERATIONS_LOG;

    /**
     * The table <code>sys.repositories</code>.
     */
    public static final Repositories REPOSITORIES = org.jooq.util.crate.sys.tables.Repositories.REPOSITORIES;

    /**
     * The table <code>sys.shards</code>.
     */
    public static final Shards SHARDS = org.jooq.util.crate.sys.tables.Shards.SHARDS;

    /**
     * The table <code>sys.snapshots</code>.
     */
    public static final Snapshots SNAPSHOTS = org.jooq.util.crate.sys.tables.Snapshots.SNAPSHOTS;
}
