/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.information_schema.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.jooq.util.crate.information_schema.InformationSchema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines extends TableImpl<Record> {

    private static final long serialVersionUID = 51658694;

    /**
     * The reference instance of <code>information_schema.routines</code>
     */
    public static final Routines ROUTINES = new Routines();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>information_schema.routines.routine_name</code>.
     */
    public final TableField<Record, String> ROUTINE_NAME = createField("routine_name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>information_schema.routines.routine_type</code>.
     */
    public final TableField<Record, String> ROUTINE_TYPE = createField("routine_type", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>information_schema.routines</code> table reference
     */
    public Routines() {
        this("routines", null);
    }

    /**
     * Create an aliased <code>information_schema.routines</code> table reference
     */
    public Routines(String alias) {
        this(alias, ROUTINES);
    }

    private Routines(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Routines(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return InformationSchema.INFORMATION_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Routines as(String alias) {
        return new Routines(alias, this);
    }

    /**
     * Rename this table
     */
    public Routines rename(String name) {
        return new Routines(name, null);
    }
}
