/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.information_schema.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.util.crate.information_schema.InformationSchema;
import org.jooq.util.crate.information_schema.Keys;
import org.jooq.util.crate.information_schema.tables.records.SchemataRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Schemata extends TableImpl<SchemataRecord> {

    private static final long serialVersionUID = -167609473;

    /**
     * The reference instance of <code>information_schema.schemata</code>
     */
    public static final Schemata SCHEMATA = new Schemata();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SchemataRecord> getRecordType() {
        return SchemataRecord.class;
    }

    /**
     * The column <code>information_schema.schemata.schema_name</code>.
     */
    public final TableField<SchemataRecord, String> SCHEMA_NAME = createField("schema_name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>information_schema.schemata</code> table reference
     */
    public Schemata() {
        this("schemata", null);
    }

    /**
     * Create an aliased <code>information_schema.schemata</code> table reference
     */
    public Schemata(String alias) {
        this(alias, SCHEMATA);
    }

    private Schemata(String alias, Table<SchemataRecord> aliased) {
        this(alias, aliased, null);
    }

    private Schemata(String alias, Table<SchemataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return InformationSchema.INFORMATION_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SchemataRecord> getPrimaryKey() {
        return Keys.PRIMARY_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SchemataRecord>> getKeys() {
        return Arrays.<UniqueKey<SchemataRecord>>asList(Keys.PRIMARY_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schemata as(String alias) {
        return new Schemata(alias, this);
    }

    /**
     * Rename this table
     */
    public Schemata rename(String name) {
        return new Schemata(name, null);
    }
}
