/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.information_schema;


import javax.annotation.Generated;

import org.jooq.util.crate.information_schema.tables.Columns;
import org.jooq.util.crate.information_schema.tables.Routines;
import org.jooq.util.crate.information_schema.tables.Schemata;
import org.jooq.util.crate.information_schema.tables.TableConstraints;
import org.jooq.util.crate.information_schema.tables.TablePartitions;


/**
 * Convenience access to all tables in information_schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>information_schema.columns</code>.
     */
    public static final Columns COLUMNS = org.jooq.util.crate.information_schema.tables.Columns.COLUMNS;

    /**
     * The table <code>information_schema.routines</code>.
     */
    public static final Routines ROUTINES = org.jooq.util.crate.information_schema.tables.Routines.ROUTINES;

    /**
     * The table <code>information_schema.schemata</code>.
     */
    public static final Schemata SCHEMATA = org.jooq.util.crate.information_schema.tables.Schemata.SCHEMATA;

    /**
     * The table <code>information_schema.table_constraints</code>.
     */
    public static final TableConstraints TABLE_CONSTRAINTS = org.jooq.util.crate.information_schema.tables.TableConstraints.TABLE_CONSTRAINTS;

    /**
     * The table <code>information_schema.table_partitions</code>.
     */
    public static final TablePartitions TABLE_PARTITIONS = org.jooq.util.crate.information_schema.tables.TablePartitions.TABLE_PARTITIONS;

    /**
     * The table <code>information_schema.tables</code>.
     */
    public static final org.jooq.util.crate.information_schema.tables.Tables TABLES = org.jooq.util.crate.information_schema.tables.Tables.TABLES;
}
