/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.sys.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.util.crate.sys.tables.JobsLog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobsLogRecord extends UpdatableRecordImpl<JobsLogRecord> implements Record5<Timestamp, String, String, Timestamp, String> {

    private static final long serialVersionUID = 862154505;

    /**
     * Setter for <code>sys.jobs_log.ended</code>.
     */
    public void setEnded(Timestamp value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>sys.jobs_log.ended</code>.
     */
    public Timestamp getEnded() {
        return (Timestamp) getValue(0);
    }

    /**
     * Setter for <code>sys.jobs_log.error</code>.
     */
    public void setError(String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>sys.jobs_log.error</code>.
     */
    public String getError() {
        return (String) getValue(1);
    }

    /**
     * Setter for <code>sys.jobs_log.id</code>.
     */
    public void setId(String value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>sys.jobs_log.id</code>.
     */
    public String getId() {
        return (String) getValue(2);
    }

    /**
     * Setter for <code>sys.jobs_log.started</code>.
     */
    public void setStarted(Timestamp value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>sys.jobs_log.started</code>.
     */
    public Timestamp getStarted() {
        return (Timestamp) getValue(3);
    }

    /**
     * Setter for <code>sys.jobs_log.stmt</code>.
     */
    public void setStmt(String value) {
        setValue(4, value);
    }

    /**
     * Getter for <code>sys.jobs_log.stmt</code>.
     */
    public String getStmt() {
        return (String) getValue(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record11<String, String, String, Integer, String, String, String, Integer, String, String, String> key() {
        return (Record11) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Timestamp, String, String, Timestamp, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Timestamp, String, String, Timestamp, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return JobsLog.JOBS_LOG.ENDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JobsLog.JOBS_LOG.ERROR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JobsLog.JOBS_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return JobsLog.JOBS_LOG.STARTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return JobsLog.JOBS_LOG.STMT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getEnded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getStarted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStmt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsLogRecord value1(Timestamp value) {
        setEnded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsLogRecord value2(String value) {
        setError(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsLogRecord value3(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsLogRecord value4(Timestamp value) {
        setStarted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsLogRecord value5(String value) {
        setStmt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsLogRecord values(Timestamp value1, String value2, String value3, Timestamp value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobsLogRecord
     */
    public JobsLogRecord() {
        super(JobsLog.JOBS_LOG);
    }

    /**
     * Create a detached, initialised JobsLogRecord
     */
    public JobsLogRecord(Timestamp ended, String error, String id, Timestamp started, String stmt) {
        super(JobsLog.JOBS_LOG);

        setValue(0, ended);
        setValue(1, error);
        setValue(2, id);
        setValue(3, started);
        setValue(4, stmt);
    }
}
