/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.sys.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;
import org.jooq.util.crate.sys.tables.Operations;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OperationsRecord extends TableRecordImpl<OperationsRecord> implements Record5<String, String, String, Timestamp, Long> {

    private static final long serialVersionUID = 1675724748;

    /**
     * Setter for <code>sys.operations.id</code>.
     */
    public void setId(String value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>sys.operations.id</code>.
     */
    public String getId() {
        return (String) getValue(0);
    }

    /**
     * Setter for <code>sys.operations.job_id</code>.
     */
    public void setJobId(String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>sys.operations.job_id</code>.
     */
    public String getJobId() {
        return (String) getValue(1);
    }

    /**
     * Setter for <code>sys.operations.name</code>.
     */
    public void setName(String value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>sys.operations.name</code>.
     */
    public String getName() {
        return (String) getValue(2);
    }

    /**
     * Setter for <code>sys.operations.started</code>.
     */
    public void setStarted(Timestamp value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>sys.operations.started</code>.
     */
    public Timestamp getStarted() {
        return (Timestamp) getValue(3);
    }

    /**
     * Setter for <code>sys.operations.used_bytes</code>.
     */
    public void setUsedBytes(Long value) {
        setValue(4, value);
    }

    /**
     * Getter for <code>sys.operations.used_bytes</code>.
     */
    public Long getUsedBytes() {
        return (Long) getValue(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Timestamp, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, Timestamp, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Operations.OPERATIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Operations.OPERATIONS.JOB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Operations.OPERATIONS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Operations.OPERATIONS.STARTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Operations.OPERATIONS.USED_BYTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getJobId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getStarted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getUsedBytes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperationsRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperationsRecord value2(String value) {
        setJobId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperationsRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperationsRecord value4(Timestamp value) {
        setStarted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperationsRecord value5(Long value) {
        setUsedBytes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperationsRecord values(String value1, String value2, String value3, Timestamp value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OperationsRecord
     */
    public OperationsRecord() {
        super(Operations.OPERATIONS);
    }

    /**
     * Create a detached, initialised OperationsRecord
     */
    public OperationsRecord(String id, String jobId, String name, Timestamp started, Long usedBytes) {
        super(Operations.OPERATIONS);

        setValue(0, id);
        setValue(1, jobId);
        setValue(2, name);
        setValue(3, started);
        setValue(4, usedBytes);
    }
}
