/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.sys.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;
import org.jooq.util.crate.sys.tables.OperationsLog;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OperationsLogRecord extends TableRecordImpl<OperationsLogRecord> implements Record7<Timestamp, String, String, String, String, Timestamp, Long> {

    private static final long serialVersionUID = 110091221;

    /**
     * Setter for <code>sys.operations_log.ended</code>.
     */
    public void setEnded(Timestamp value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>sys.operations_log.ended</code>.
     */
    public Timestamp getEnded() {
        return (Timestamp) getValue(0);
    }

    /**
     * Setter for <code>sys.operations_log.error</code>.
     */
    public void setError(String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>sys.operations_log.error</code>.
     */
    public String getError() {
        return (String) getValue(1);
    }

    /**
     * Setter for <code>sys.operations_log.id</code>.
     */
    public void setId(String value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>sys.operations_log.id</code>.
     */
    public String getId() {
        return (String) getValue(2);
    }

    /**
     * Setter for <code>sys.operations_log.job_id</code>.
     */
    public void setJobId(String value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>sys.operations_log.job_id</code>.
     */
    public String getJobId() {
        return (String) getValue(3);
    }

    /**
     * Setter for <code>sys.operations_log.name</code>.
     */
    public void setName(String value) {
        setValue(4, value);
    }

    /**
     * Getter for <code>sys.operations_log.name</code>.
     */
    public String getName() {
        return (String) getValue(4);
    }

    /**
     * Setter for <code>sys.operations_log.started</code>.
     */
    public void setStarted(Timestamp value) {
        setValue(5, value);
    }

    /**
     * Getter for <code>sys.operations_log.started</code>.
     */
    public Timestamp getStarted() {
        return (Timestamp) getValue(5);
    }

    /**
     * Setter for <code>sys.operations_log.used_bytes</code>.
     */
    public void setUsedBytes(Long value) {
        setValue(6, value);
    }

    /**
     * Getter for <code>sys.operations_log.used_bytes</code>.
     */
    public Long getUsedBytes() {
        return (Long) getValue(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Timestamp, String, String, String, String, Timestamp, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Timestamp, String, String, String, String, Timestamp, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return OperationsLog.OPERATIONS_LOG.ENDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OperationsLog.OPERATIONS_LOG.ERROR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return OperationsLog.OPERATIONS_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return OperationsLog.OPERATIONS_LOG.JOB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return OperationsLog.OPERATIONS_LOG.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return OperationsLog.OPERATIONS_LOG.STARTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return OperationsLog.OPERATIONS_LOG.USED_BYTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getEnded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getJobId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getStarted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getUsedBytes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperationsLogRecord value1(Timestamp value) {
        setEnded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperationsLogRecord value2(String value) {
        setError(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperationsLogRecord value3(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperationsLogRecord value4(String value) {
        setJobId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperationsLogRecord value5(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperationsLogRecord value6(Timestamp value) {
        setStarted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperationsLogRecord value7(Long value) {
        setUsedBytes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperationsLogRecord values(Timestamp value1, String value2, String value3, String value4, String value5, Timestamp value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OperationsLogRecord
     */
    public OperationsLogRecord() {
        super(OperationsLog.OPERATIONS_LOG);
    }

    /**
     * Create a detached, initialised OperationsLogRecord
     */
    public OperationsLogRecord(Timestamp ended, String error, String id, String jobId, String name, Timestamp started, Long usedBytes) {
        super(OperationsLog.OPERATIONS_LOG);

        setValue(0, ended);
        setValue(1, error);
        setValue(2, id);
        setValue(3, jobId);
        setValue(4, name);
        setValue(5, started);
        setValue(6, usedBytes);
    }
}
