/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.sys.tables.records;


import javax.annotation.Generated;

import org.jooq.Record11;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.util.crate.sys.tables.Shards;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShardsRecord extends UpdatableRecordImpl<ShardsRecord> {

    private static final long serialVersionUID = -1646349758;

    /**
     * Setter for <code>sys.shards.id</code>.
     */
    public void setId(Integer value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>sys.shards.id</code>.
     */
    public Integer getId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for <code>sys.shards.num_docs</code>.
     */
    public void setNumDocs(Long value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>sys.shards.num_docs</code>.
     */
    public Long getNumDocs() {
        return (Long) getValue(1);
    }

    /**
     * Setter for <code>sys.shards.orphan_partition</code>.
     */
    public void setOrphanPartition(Boolean value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>sys.shards.orphan_partition</code>.
     */
    public Boolean getOrphanPartition() {
        return (Boolean) getValue(2);
    }

    /**
     * Setter for <code>sys.shards.partition_ident</code>.
     */
    public void setPartitionIdent(String value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>sys.shards.partition_ident</code>.
     */
    public String getPartitionIdent() {
        return (String) getValue(3);
    }

    /**
     * Setter for <code>sys.shards.primary</code>.
     */
    public void setPrimary(Boolean value) {
        setValue(4, value);
    }

    /**
     * Getter for <code>sys.shards.primary</code>.
     */
    public Boolean getPrimary() {
        return (Boolean) getValue(4);
    }

    /**
     * Setter for <code>sys.shards.recovery</code>.
     */
    public void setRecovery(Object value) {
        setValue(5, value);
    }

    /**
     * Getter for <code>sys.shards.recovery</code>.
     */
    public Object getRecovery() {
        return (Object) getValue(5);
    }

    /**
     * Setter for <code>sys.shards.recovery['files']</code>.
     */
    public void setRecovery_5b_27files_27_5d(Object value) {
        setValue(6, value);
    }

    /**
     * Getter for <code>sys.shards.recovery['files']</code>.
     */
    public Object getRecovery_5b_27files_27_5d() {
        return (Object) getValue(6);
    }

    /**
     * Setter for <code>sys.shards.recovery['files']['percent']</code>.
     */
    public void setRecovery_5b_27files_27_5d_5b_27percent_27_5d(Float value) {
        setValue(7, value);
    }

    /**
     * Getter for <code>sys.shards.recovery['files']['percent']</code>.
     */
    public Float getRecovery_5b_27files_27_5d_5b_27percent_27_5d() {
        return (Float) getValue(7);
    }

    /**
     * Setter for <code>sys.shards.recovery['files']['recovered']</code>.
     */
    public void setRecovery_5b_27files_27_5d_5b_27recovered_27_5d(Integer value) {
        setValue(8, value);
    }

    /**
     * Getter for <code>sys.shards.recovery['files']['recovered']</code>.
     */
    public Integer getRecovery_5b_27files_27_5d_5b_27recovered_27_5d() {
        return (Integer) getValue(8);
    }

    /**
     * Setter for <code>sys.shards.recovery['files']['reused']</code>.
     */
    public void setRecovery_5b_27files_27_5d_5b_27reused_27_5d(Integer value) {
        setValue(9, value);
    }

    /**
     * Getter for <code>sys.shards.recovery['files']['reused']</code>.
     */
    public Integer getRecovery_5b_27files_27_5d_5b_27reused_27_5d() {
        return (Integer) getValue(9);
    }

    /**
     * Setter for <code>sys.shards.recovery['files']['used']</code>.
     */
    public void setRecovery_5b_27files_27_5d_5b_27used_27_5d(Integer value) {
        setValue(10, value);
    }

    /**
     * Getter for <code>sys.shards.recovery['files']['used']</code>.
     */
    public Integer getRecovery_5b_27files_27_5d_5b_27used_27_5d() {
        return (Integer) getValue(10);
    }

    /**
     * Setter for <code>sys.shards.recovery['size']</code>.
     */
    public void setRecovery_5b_27size_27_5d(Object value) {
        setValue(11, value);
    }

    /**
     * Getter for <code>sys.shards.recovery['size']</code>.
     */
    public Object getRecovery_5b_27size_27_5d() {
        return (Object) getValue(11);
    }

    /**
     * Setter for <code>sys.shards.recovery['size']['percent']</code>.
     */
    public void setRecovery_5b_27size_27_5d_5b_27percent_27_5d(Float value) {
        setValue(12, value);
    }

    /**
     * Getter for <code>sys.shards.recovery['size']['percent']</code>.
     */
    public Float getRecovery_5b_27size_27_5d_5b_27percent_27_5d() {
        return (Float) getValue(12);
    }

    /**
     * Setter for <code>sys.shards.recovery['size']['recovered']</code>.
     */
    public void setRecovery_5b_27size_27_5d_5b_27recovered_27_5d(Long value) {
        setValue(13, value);
    }

    /**
     * Getter for <code>sys.shards.recovery['size']['recovered']</code>.
     */
    public Long getRecovery_5b_27size_27_5d_5b_27recovered_27_5d() {
        return (Long) getValue(13);
    }

    /**
     * Setter for <code>sys.shards.recovery['size']['reused']</code>.
     */
    public void setRecovery_5b_27size_27_5d_5b_27reused_27_5d(Long value) {
        setValue(14, value);
    }

    /**
     * Getter for <code>sys.shards.recovery['size']['reused']</code>.
     */
    public Long getRecovery_5b_27size_27_5d_5b_27reused_27_5d() {
        return (Long) getValue(14);
    }

    /**
     * Setter for <code>sys.shards.recovery['size']['used']</code>.
     */
    public void setRecovery_5b_27size_27_5d_5b_27used_27_5d(Long value) {
        setValue(15, value);
    }

    /**
     * Getter for <code>sys.shards.recovery['size']['used']</code>.
     */
    public Long getRecovery_5b_27size_27_5d_5b_27used_27_5d() {
        return (Long) getValue(15);
    }

    /**
     * Setter for <code>sys.shards.recovery['stage']</code>.
     */
    public void setRecovery_5b_27stage_27_5d(String value) {
        setValue(16, value);
    }

    /**
     * Getter for <code>sys.shards.recovery['stage']</code>.
     */
    public String getRecovery_5b_27stage_27_5d() {
        return (String) getValue(16);
    }

    /**
     * Setter for <code>sys.shards.recovery['total_time']</code>.
     */
    public void setRecovery_5b_27totalTime_27_5d(Long value) {
        setValue(17, value);
    }

    /**
     * Getter for <code>sys.shards.recovery['total_time']</code>.
     */
    public Long getRecovery_5b_27totalTime_27_5d() {
        return (Long) getValue(17);
    }

    /**
     * Setter for <code>sys.shards.recovery['type']</code>.
     */
    public void setRecovery_5b_27type_27_5d(String value) {
        setValue(18, value);
    }

    /**
     * Getter for <code>sys.shards.recovery['type']</code>.
     */
    public String getRecovery_5b_27type_27_5d() {
        return (String) getValue(18);
    }

    /**
     * Setter for <code>sys.shards.relocating_node</code>.
     */
    public void setRelocatingNode(String value) {
        setValue(19, value);
    }

    /**
     * Getter for <code>sys.shards.relocating_node</code>.
     */
    public String getRelocatingNode() {
        return (String) getValue(19);
    }

    /**
     * Setter for <code>sys.shards.schema_name</code>.
     */
    public void setSchemaName(String value) {
        setValue(20, value);
    }

    /**
     * Getter for <code>sys.shards.schema_name</code>.
     */
    public String getSchemaName() {
        return (String) getValue(20);
    }

    /**
     * Setter for <code>sys.shards.size</code>.
     */
    public void setSize(Long value) {
        setValue(21, value);
    }

    /**
     * Getter for <code>sys.shards.size</code>.
     */
    public Long getSize() {
        return (Long) getValue(21);
    }

    /**
     * Setter for <code>sys.shards.state</code>.
     */
    public void setState(String value) {
        setValue(22, value);
    }

    /**
     * Getter for <code>sys.shards.state</code>.
     */
    public String getState() {
        return (String) getValue(22);
    }

    /**
     * Setter for <code>sys.shards.table_name</code>.
     */
    public void setTableName(String value) {
        setValue(23, value);
    }

    /**
     * Getter for <code>sys.shards.table_name</code>.
     */
    public String getTableName() {
        return (String) getValue(23);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record11<String, String, String, Integer, String, String, String, Integer, String, String, String> key() {
        return (Record11) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShardsRecord
     */
    public ShardsRecord() {
        super(Shards.SHARDS);
    }

    /**
     * Create a detached, initialised ShardsRecord
     */
    public ShardsRecord(Integer id, Long numDocs, Boolean orphanPartition, String partitionIdent, Boolean primary, Object recovery, Object recovery_5b_27files_27_5d, Float recovery_5b_27files_27_5d_5b_27percent_27_5d, Integer recovery_5b_27files_27_5d_5b_27recovered_27_5d, Integer recovery_5b_27files_27_5d_5b_27reused_27_5d, Integer recovery_5b_27files_27_5d_5b_27used_27_5d, Object recovery_5b_27size_27_5d, Float recovery_5b_27size_27_5d_5b_27percent_27_5d, Long recovery_5b_27size_27_5d_5b_27recovered_27_5d, Long recovery_5b_27size_27_5d_5b_27reused_27_5d, Long recovery_5b_27size_27_5d_5b_27used_27_5d, String recovery_5b_27stage_27_5d, Long recovery_5b_27totalTime_27_5d, String recovery_5b_27type_27_5d, String relocatingNode, String schemaName, Long size, String state, String tableName) {
        super(Shards.SHARDS);

        setValue(0, id);
        setValue(1, numDocs);
        setValue(2, orphanPartition);
        setValue(3, partitionIdent);
        setValue(4, primary);
        setValue(5, recovery);
        setValue(6, recovery_5b_27files_27_5d);
        setValue(7, recovery_5b_27files_27_5d_5b_27percent_27_5d);
        setValue(8, recovery_5b_27files_27_5d_5b_27recovered_27_5d);
        setValue(9, recovery_5b_27files_27_5d_5b_27reused_27_5d);
        setValue(10, recovery_5b_27files_27_5d_5b_27used_27_5d);
        setValue(11, recovery_5b_27size_27_5d);
        setValue(12, recovery_5b_27size_27_5d_5b_27percent_27_5d);
        setValue(13, recovery_5b_27size_27_5d_5b_27recovered_27_5d);
        setValue(14, recovery_5b_27size_27_5d_5b_27reused_27_5d);
        setValue(15, recovery_5b_27size_27_5d_5b_27used_27_5d);
        setValue(16, recovery_5b_27stage_27_5d);
        setValue(17, recovery_5b_27totalTime_27_5d);
        setValue(18, recovery_5b_27type_27_5d);
        setValue(19, relocatingNode);
        setValue(20, schemaName);
        setValue(21, size);
        setValue(22, state);
        setValue(23, tableName);
    }
}
