/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.sys.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.jooq.util.crate.sys.Sys;
import org.jooq.util.crate.sys.tables.records.ChecksRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Checks extends TableImpl<ChecksRecord> {

    private static final long serialVersionUID = -953429586;

    /**
     * The reference instance of <code>sys.checks</code>
     */
    public static final Checks CHECKS = new Checks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChecksRecord> getRecordType() {
        return ChecksRecord.class;
    }

    /**
     * The column <code>sys.checks.description</code>.
     */
    public final TableField<ChecksRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>sys.checks.id</code>.
     */
    public final TableField<ChecksRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>sys.checks.passed</code>.
     */
    public final TableField<ChecksRecord, Boolean> PASSED = createField("passed", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>sys.checks.severity</code>.
     */
    public final TableField<ChecksRecord, Integer> SEVERITY = createField("severity", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>sys.checks</code> table reference
     */
    public Checks() {
        this("checks", null);
    }

    /**
     * Create an aliased <code>sys.checks</code> table reference
     */
    public Checks(String alias) {
        this(alias, CHECKS);
    }

    private Checks(String alias, Table<ChecksRecord> aliased) {
        this(alias, aliased, null);
    }

    private Checks(String alias, Table<ChecksRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sys.SYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Checks as(String alias) {
        return new Checks(alias, this);
    }

    /**
     * Rename this table
     */
    public Checks rename(String name) {
        return new Checks(name, null);
    }
}
