/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.sys.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.jooq.util.crate.sys.Sys;
import org.jooq.util.crate.sys.tables.records.JobsLogRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobsLog extends TableImpl<JobsLogRecord> {

    private static final long serialVersionUID = 1265922673;

    /**
     * The reference instance of <code>sys.jobs_log</code>
     */
    public static final JobsLog JOBS_LOG = new JobsLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JobsLogRecord> getRecordType() {
        return JobsLogRecord.class;
    }

    /**
     * The column <code>sys.jobs_log.ended</code>.
     */
    public final TableField<JobsLogRecord, Timestamp> ENDED = createField("ended", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sys.jobs_log.error</code>.
     */
    public final TableField<JobsLogRecord, String> ERROR = createField("error", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>sys.jobs_log.id</code>.
     */
    public final TableField<JobsLogRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>sys.jobs_log.started</code>.
     */
    public final TableField<JobsLogRecord, Timestamp> STARTED = createField("started", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sys.jobs_log.stmt</code>.
     */
    public final TableField<JobsLogRecord, String> STMT = createField("stmt", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>sys.jobs_log</code> table reference
     */
    public JobsLog() {
        this("jobs_log", null);
    }

    /**
     * Create an aliased <code>sys.jobs_log</code> table reference
     */
    public JobsLog(String alias) {
        this(alias, JOBS_LOG);
    }

    private JobsLog(String alias, Table<JobsLogRecord> aliased) {
        this(alias, aliased, null);
    }

    private JobsLog(String alias, Table<JobsLogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sys.SYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsLog as(String alias) {
        return new JobsLog(alias, this);
    }

    /**
     * Rename this table
     */
    public JobsLog rename(String name) {
        return new JobsLog(name, null);
    }
}
