/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.sys.tables;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.jooq.util.crate.sys.Sys;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Operations extends TableImpl<Record> {

    private static final long serialVersionUID = 2067539965;

    /**
     * The reference instance of <code>sys.operations</code>
     */
    public static final Operations OPERATIONS = new Operations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>sys.operations.id</code>.
     */
    public final TableField<Record, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>sys.operations.job_id</code>.
     */
    public final TableField<Record, String> JOB_ID = createField("job_id", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>sys.operations.name</code>.
     */
    public final TableField<Record, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>sys.operations.started</code>.
     */
    public final TableField<Record, Timestamp> STARTED = createField("started", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sys.operations.used_bytes</code>.
     */
    public final TableField<Record, Long> USED_BYTES = createField("used_bytes", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>sys.operations</code> table reference
     */
    public Operations() {
        this("operations", null);
    }

    /**
     * Create an aliased <code>sys.operations</code> table reference
     */
    public Operations(String alias) {
        this(alias, OPERATIONS);
    }

    private Operations(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Operations(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sys.SYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Operations as(String alias) {
        return new Operations(alias, this);
    }

    /**
     * Rename this table
     */
    public Operations rename(String name) {
        return new Operations(name, null);
    }
}
