/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.sys.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.util.crate.sys.Keys;
import org.jooq.util.crate.sys.Sys;
import org.jooq.util.crate.sys.tables.records.SnapshotsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Snapshots extends TableImpl<SnapshotsRecord> {

    private static final long serialVersionUID = -27789859;

    /**
     * The reference instance of <code>sys.snapshots</code>
     */
    public static final Snapshots SNAPSHOTS = new Snapshots();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SnapshotsRecord> getRecordType() {
        return SnapshotsRecord.class;
    }

    /**
     * The column <code>sys.snapshots.concrete_indices</code>.
     */
    public final TableField<SnapshotsRecord, String[]> CONCRETE_INDICES = createField("concrete_indices", org.jooq.impl.SQLDataType.VARCHAR.getArrayDataType(), this, "");

    /**
     * The column <code>sys.snapshots.finished</code>.
     */
    public final TableField<SnapshotsRecord, Timestamp> FINISHED = createField("finished", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sys.snapshots.name</code>.
     */
    public final TableField<SnapshotsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>sys.snapshots.repository</code>.
     */
    public final TableField<SnapshotsRecord, String> REPOSITORY = createField("repository", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>sys.snapshots.started</code>.
     */
    public final TableField<SnapshotsRecord, Timestamp> STARTED = createField("started", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sys.snapshots.state</code>.
     */
    public final TableField<SnapshotsRecord, String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>sys.snapshots.version</code>.
     */
    public final TableField<SnapshotsRecord, String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>sys.snapshots</code> table reference
     */
    public Snapshots() {
        this("snapshots", null);
    }

    /**
     * Create an aliased <code>sys.snapshots</code> table reference
     */
    public Snapshots(String alias) {
        this(alias, SNAPSHOTS);
    }

    private Snapshots(String alias, Table<SnapshotsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Snapshots(String alias, Table<SnapshotsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sys.SYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SnapshotsRecord> getPrimaryKey() {
        return Keys.PRIMARY_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SnapshotsRecord>> getKeys() {
        return Arrays.<UniqueKey<SnapshotsRecord>>asList(Keys.PRIMARY_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Snapshots as(String alias) {
        return new Snapshots(alias, this);
    }

    /**
     * Rename this table
     */
    public Snapshots rename(String name) {
        return new Snapshots(name, null);
    }
}
