/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.information_schema.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;
import org.jooq.util.crate.information_schema.tables.Routines;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutinesRecord extends TableRecordImpl<RoutinesRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1128887837;

    /**
     * Setter for <code>information_schema.routines.routine_name</code>.
     */
    public void setRoutineName(String value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>information_schema.routines.routine_name</code>.
     */
    public String getRoutineName() {
        return (String) getValue(0);
    }

    /**
     * Setter for <code>information_schema.routines.routine_type</code>.
     */
    public void setRoutineType(String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>information_schema.routines.routine_type</code>.
     */
    public String getRoutineType() {
        return (String) getValue(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Routines.ROUTINES.ROUTINE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Routines.ROUTINES.ROUTINE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRoutineName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRoutineType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoutinesRecord value1(String value) {
        setRoutineName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoutinesRecord value2(String value) {
        setRoutineType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoutinesRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoutinesRecord
     */
    public RoutinesRecord() {
        super(Routines.ROUTINES);
    }

    /**
     * Create a detached, initialised RoutinesRecord
     */
    public RoutinesRecord(String routineName, String routineType) {
        super(Routines.ROUTINES);

        setValue(0, routineName);
        setValue(1, routineType);
    }
}
