/**
 * This class is generated by jOOQ
 */
package org.jooq.util.crate.information_schema.tables.records;


import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;
import org.jooq.util.crate.information_schema.tables.Tables;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TablesRecord extends TableRecordImpl<TablesRecord> {

    private static final long serialVersionUID = -534240913;

    /**
     * Setter for <code>information_schema.tables.blobs_path</code>.
     */
    public void setBlobsPath(String value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>information_schema.tables.blobs_path</code>.
     */
    public String getBlobsPath() {
        return (String) getValue(0);
    }

    /**
     * Setter for <code>information_schema.tables.clustered_by</code>.
     */
    public void setClusteredBy(String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>information_schema.tables.clustered_by</code>.
     */
    public String getClusteredBy() {
        return (String) getValue(1);
    }

    /**
     * Setter for <code>information_schema.tables.column_policy</code>.
     */
    public void setColumnPolicy(String value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>information_schema.tables.column_policy</code>.
     */
    public String getColumnPolicy() {
        return (String) getValue(2);
    }

    /**
     * Setter for <code>information_schema.tables.number_of_replicas</code>.
     */
    public void setNumberOfReplicas(String value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>information_schema.tables.number_of_replicas</code>.
     */
    public String getNumberOfReplicas() {
        return (String) getValue(3);
    }

    /**
     * Setter for <code>information_schema.tables.number_of_shards</code>.
     */
    public void setNumberOfShards(Integer value) {
        setValue(4, value);
    }

    /**
     * Getter for <code>information_schema.tables.number_of_shards</code>.
     */
    public Integer getNumberOfShards() {
        return (Integer) getValue(4);
    }

    /**
     * Setter for <code>information_schema.tables.partitioned_by</code>.
     */
    public void setPartitionedBy(String[] value) {
        setValue(5, value);
    }

    /**
     * Getter for <code>information_schema.tables.partitioned_by</code>.
     */
    public String[] getPartitionedBy() {
        return (String[]) getValue(5);
    }

    /**
     * Setter for <code>information_schema.tables.schema_name</code>.
     */
    public void setSchemaName(String value) {
        setValue(6, value);
    }

    /**
     * Getter for <code>information_schema.tables.schema_name</code>.
     */
    public String getSchemaName() {
        return (String) getValue(6);
    }

    /**
     * Setter for <code>information_schema.tables.settings</code>.
     */
    public void setSettings(Object value) {
        setValue(7, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings</code>.
     */
    public Object getSettings() {
        return (Object) getValue(7);
    }

    /**
     * Setter for <code>information_schema.tables.settings['blocks']</code>.
     */
    public void setSettings_5b_27blocks_27_5d(Object value) {
        setValue(8, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['blocks']</code>.
     */
    public Object getSettings_5b_27blocks_27_5d() {
        return (Object) getValue(8);
    }

    /**
     * Setter for <code>information_schema.tables.settings['blocks']['metadata']</code>.
     */
    public void setSettings_5b_27blocks_27_5d_5b_27metadata_27_5d(Boolean value) {
        setValue(9, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['blocks']['metadata']</code>.
     */
    public Boolean getSettings_5b_27blocks_27_5d_5b_27metadata_27_5d() {
        return (Boolean) getValue(9);
    }

    /**
     * Setter for <code>information_schema.tables.settings['blocks']['read']</code>.
     */
    public void setSettings_5b_27blocks_27_5d_5b_27read_27_5d(Boolean value) {
        setValue(10, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['blocks']['read']</code>.
     */
    public Boolean getSettings_5b_27blocks_27_5d_5b_27read_27_5d() {
        return (Boolean) getValue(10);
    }

    /**
     * Setter for <code>information_schema.tables.settings['blocks']['read_only']</code>.
     */
    public void setSettings_5b_27blocks_27_5d_5b_27readOnly_27_5d(Boolean value) {
        setValue(11, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['blocks']['read_only']</code>.
     */
    public Boolean getSettings_5b_27blocks_27_5d_5b_27readOnly_27_5d() {
        return (Boolean) getValue(11);
    }

    /**
     * Setter for <code>information_schema.tables.settings['blocks']['write']</code>.
     */
    public void setSettings_5b_27blocks_27_5d_5b_27write_27_5d(Boolean value) {
        setValue(12, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['blocks']['write']</code>.
     */
    public Boolean getSettings_5b_27blocks_27_5d_5b_27write_27_5d() {
        return (Boolean) getValue(12);
    }

    /**
     * Setter for <code>information_schema.tables.settings['gateway']</code>.
     */
    public void setSettings_5b_27gateway_27_5d(Object value) {
        setValue(13, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['gateway']</code>.
     */
    public Object getSettings_5b_27gateway_27_5d() {
        return (Object) getValue(13);
    }

    /**
     * Setter for <code>information_schema.tables.settings['gateway']['local']</code>.
     */
    public void setSettings_5b_27gateway_27_5d_5b_27local_27_5d(Object value) {
        setValue(14, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['gateway']['local']</code>.
     */
    public Object getSettings_5b_27gateway_27_5d_5b_27local_27_5d() {
        return (Object) getValue(14);
    }

    /**
     * Setter for <code>information_schema.tables.settings['gateway']['local']['sync']</code>.
     */
    public void setSettings_5b_27gateway_27_5d_5b_27local_27_5d_5b_27sync_27_5d(Long value) {
        setValue(15, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['gateway']['local']['sync']</code>.
     */
    public Long getSettings_5b_27gateway_27_5d_5b_27local_27_5d_5b_27sync_27_5d() {
        return (Long) getValue(15);
    }

    /**
     * Setter for <code>information_schema.tables.settings['recovery']</code>.
     */
    public void setSettings_5b_27recovery_27_5d(Object value) {
        setValue(16, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['recovery']</code>.
     */
    public Object getSettings_5b_27recovery_27_5d() {
        return (Object) getValue(16);
    }

    /**
     * Setter for <code>information_schema.tables.settings['recovery']['initial_shards']</code>.
     */
    public void setSettings_5b_27recovery_27_5d_5b_27initialShards_27_5d(String value) {
        setValue(17, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['recovery']['initial_shards']</code>.
     */
    public String getSettings_5b_27recovery_27_5d_5b_27initialShards_27_5d() {
        return (String) getValue(17);
    }

    /**
     * Setter for <code>information_schema.tables.settings['refresh_interval']</code>.
     */
    public void setSettings_5b_27refreshInterval_27_5d(Long value) {
        setValue(18, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['refresh_interval']</code>.
     */
    public Long getSettings_5b_27refreshInterval_27_5d() {
        return (Long) getValue(18);
    }

    /**
     * Setter for <code>information_schema.tables.settings['routing']</code>.
     */
    public void setSettings_5b_27routing_27_5d(Object value) {
        setValue(19, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['routing']</code>.
     */
    public Object getSettings_5b_27routing_27_5d() {
        return (Object) getValue(19);
    }

    /**
     * Setter for <code>information_schema.tables.settings['routing']['allocation']</code>.
     */
    public void setSettings_5b_27routing_27_5d_5b_27allocation_27_5d(Object value) {
        setValue(20, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['routing']['allocation']</code>.
     */
    public Object getSettings_5b_27routing_27_5d_5b_27allocation_27_5d() {
        return (Object) getValue(20);
    }

    /**
     * Setter for <code>information_schema.tables.settings['routing']['allocation']['enable']</code>.
     */
    public void setSettings_5b_27routing_27_5d_5b_27allocation_27_5d_5b_27enable_27_5d(String value) {
        setValue(21, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['routing']['allocation']['enable']</code>.
     */
    public String getSettings_5b_27routing_27_5d_5b_27allocation_27_5d_5b_27enable_27_5d() {
        return (String) getValue(21);
    }

    /**
     * Setter for <code>information_schema.tables.settings['routing']['allocation']['total_shards_per_node']</code>.
     */
    public void setSettings_5b_27routing_27_5d_5b_27allocation_27_5d_5b_27totalShardsPerNode_27_5d(Integer value) {
        setValue(22, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['routing']['allocation']['total_shards_per_node']</code>.
     */
    public Integer getSettings_5b_27routing_27_5d_5b_27allocation_27_5d_5b_27totalShardsPerNode_27_5d() {
        return (Integer) getValue(22);
    }

    /**
     * Setter for <code>information_schema.tables.settings['translog']</code>.
     */
    public void setSettings_5b_27translog_27_5d(Object value) {
        setValue(23, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['translog']</code>.
     */
    public Object getSettings_5b_27translog_27_5d() {
        return (Object) getValue(23);
    }

    /**
     * Setter for <code>information_schema.tables.settings['translog']['disable_flush']</code>.
     */
    public void setSettings_5b_27translog_27_5d_5b_27disableFlush_27_5d(Boolean value) {
        setValue(24, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['translog']['disable_flush']</code>.
     */
    public Boolean getSettings_5b_27translog_27_5d_5b_27disableFlush_27_5d() {
        return (Boolean) getValue(24);
    }

    /**
     * Setter for <code>information_schema.tables.settings['translog']['flush_threshold_ops']</code>.
     */
    public void setSettings_5b_27translog_27_5d_5b_27flushThresholdOps_27_5d(Integer value) {
        setValue(25, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['translog']['flush_threshold_ops']</code>.
     */
    public Integer getSettings_5b_27translog_27_5d_5b_27flushThresholdOps_27_5d() {
        return (Integer) getValue(25);
    }

    /**
     * Setter for <code>information_schema.tables.settings['translog']['flush_threshold_period']</code>.
     */
    public void setSettings_5b_27translog_27_5d_5b_27flushThresholdPeriod_27_5d(Long value) {
        setValue(26, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['translog']['flush_threshold_period']</code>.
     */
    public Long getSettings_5b_27translog_27_5d_5b_27flushThresholdPeriod_27_5d() {
        return (Long) getValue(26);
    }

    /**
     * Setter for <code>information_schema.tables.settings['translog']['flush_threshold_size']</code>.
     */
    public void setSettings_5b_27translog_27_5d_5b_27flushThresholdSize_27_5d(Long value) {
        setValue(27, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['translog']['flush_threshold_size']</code>.
     */
    public Long getSettings_5b_27translog_27_5d_5b_27flushThresholdSize_27_5d() {
        return (Long) getValue(27);
    }

    /**
     * Setter for <code>information_schema.tables.settings['translog']['interval']</code>.
     */
    public void setSettings_5b_27translog_27_5d_5b_27interval_27_5d(Long value) {
        setValue(28, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['translog']['interval']</code>.
     */
    public Long getSettings_5b_27translog_27_5d_5b_27interval_27_5d() {
        return (Long) getValue(28);
    }

    /**
     * Setter for <code>information_schema.tables.settings['unassigned']</code>.
     */
    public void setSettings_5b_27unassigned_27_5d(Object value) {
        setValue(29, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['unassigned']</code>.
     */
    public Object getSettings_5b_27unassigned_27_5d() {
        return (Object) getValue(29);
    }

    /**
     * Setter for <code>information_schema.tables.settings['unassigned']['node_left']</code>.
     */
    public void setSettings_5b_27unassigned_27_5d_5b_27nodeLeft_27_5d(Object value) {
        setValue(30, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['unassigned']['node_left']</code>.
     */
    public Object getSettings_5b_27unassigned_27_5d_5b_27nodeLeft_27_5d() {
        return (Object) getValue(30);
    }

    /**
     * Setter for <code>information_schema.tables.settings['unassigned']['node_left']['delayed_timeout']</code>.
     */
    public void setSettings_5b_27unassigned_27_5d_5b_27nodeLeft_27_5d_5b_27delayedTimeout_27_5d(Long value) {
        setValue(31, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['unassigned']['node_left']['delayed_timeout']</code>.
     */
    public Long getSettings_5b_27unassigned_27_5d_5b_27nodeLeft_27_5d_5b_27delayedTimeout_27_5d() {
        return (Long) getValue(31);
    }

    /**
     * Setter for <code>information_schema.tables.settings['warmer']</code>.
     */
    public void setSettings_5b_27warmer_27_5d(Object value) {
        setValue(32, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['warmer']</code>.
     */
    public Object getSettings_5b_27warmer_27_5d() {
        return (Object) getValue(32);
    }

    /**
     * Setter for <code>information_schema.tables.settings['warmer']['enabled']</code>.
     */
    public void setSettings_5b_27warmer_27_5d_5b_27enabled_27_5d(Boolean value) {
        setValue(33, value);
    }

    /**
     * Getter for <code>information_schema.tables.settings['warmer']['enabled']</code>.
     */
    public Boolean getSettings_5b_27warmer_27_5d_5b_27enabled_27_5d() {
        return (Boolean) getValue(33);
    }

    /**
     * Setter for <code>information_schema.tables.table_name</code>.
     */
    public void setTableName(String value) {
        setValue(34, value);
    }

    /**
     * Getter for <code>information_schema.tables.table_name</code>.
     */
    public String getTableName() {
        return (String) getValue(34);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TablesRecord
     */
    public TablesRecord() {
        super(Tables.TABLES);
    }

    /**
     * Create a detached, initialised TablesRecord
     */
    public TablesRecord(String blobsPath, String clusteredBy, String columnPolicy, String numberOfReplicas, Integer numberOfShards, String[] partitionedBy, String schemaName, Object settings, Object settings_5b_27blocks_27_5d, Boolean settings_5b_27blocks_27_5d_5b_27metadata_27_5d, Boolean settings_5b_27blocks_27_5d_5b_27read_27_5d, Boolean settings_5b_27blocks_27_5d_5b_27readOnly_27_5d, Boolean settings_5b_27blocks_27_5d_5b_27write_27_5d, Object settings_5b_27gateway_27_5d, Object settings_5b_27gateway_27_5d_5b_27local_27_5d, Long settings_5b_27gateway_27_5d_5b_27local_27_5d_5b_27sync_27_5d, Object settings_5b_27recovery_27_5d, String settings_5b_27recovery_27_5d_5b_27initialShards_27_5d, Long settings_5b_27refreshInterval_27_5d, Object settings_5b_27routing_27_5d, Object settings_5b_27routing_27_5d_5b_27allocation_27_5d, String settings_5b_27routing_27_5d_5b_27allocation_27_5d_5b_27enable_27_5d, Integer settings_5b_27routing_27_5d_5b_27allocation_27_5d_5b_27totalShardsPerNode_27_5d, Object settings_5b_27translog_27_5d, Boolean settings_5b_27translog_27_5d_5b_27disableFlush_27_5d, Integer settings_5b_27translog_27_5d_5b_27flushThresholdOps_27_5d, Long settings_5b_27translog_27_5d_5b_27flushThresholdPeriod_27_5d, Long settings_5b_27translog_27_5d_5b_27flushThresholdSize_27_5d, Long settings_5b_27translog_27_5d_5b_27interval_27_5d, Object settings_5b_27unassigned_27_5d, Object settings_5b_27unassigned_27_5d_5b_27nodeLeft_27_5d, Long settings_5b_27unassigned_27_5d_5b_27nodeLeft_27_5d_5b_27delayedTimeout_27_5d, Object settings_5b_27warmer_27_5d, Boolean settings_5b_27warmer_27_5d_5b_27enabled_27_5d, String tableName) {
        super(Tables.TABLES);

        setValue(0, blobsPath);
        setValue(1, clusteredBy);
        setValue(2, columnPolicy);
        setValue(3, numberOfReplicas);
        setValue(4, numberOfShards);
        setValue(5, partitionedBy);
        setValue(6, schemaName);
        setValue(7, settings);
        setValue(8, settings_5b_27blocks_27_5d);
        setValue(9, settings_5b_27blocks_27_5d_5b_27metadata_27_5d);
        setValue(10, settings_5b_27blocks_27_5d_5b_27read_27_5d);
        setValue(11, settings_5b_27blocks_27_5d_5b_27readOnly_27_5d);
        setValue(12, settings_5b_27blocks_27_5d_5b_27write_27_5d);
        setValue(13, settings_5b_27gateway_27_5d);
        setValue(14, settings_5b_27gateway_27_5d_5b_27local_27_5d);
        setValue(15, settings_5b_27gateway_27_5d_5b_27local_27_5d_5b_27sync_27_5d);
        setValue(16, settings_5b_27recovery_27_5d);
        setValue(17, settings_5b_27recovery_27_5d_5b_27initialShards_27_5d);
        setValue(18, settings_5b_27refreshInterval_27_5d);
        setValue(19, settings_5b_27routing_27_5d);
        setValue(20, settings_5b_27routing_27_5d_5b_27allocation_27_5d);
        setValue(21, settings_5b_27routing_27_5d_5b_27allocation_27_5d_5b_27enable_27_5d);
        setValue(22, settings_5b_27routing_27_5d_5b_27allocation_27_5d_5b_27totalShardsPerNode_27_5d);
        setValue(23, settings_5b_27translog_27_5d);
        setValue(24, settings_5b_27translog_27_5d_5b_27disableFlush_27_5d);
        setValue(25, settings_5b_27translog_27_5d_5b_27flushThresholdOps_27_5d);
        setValue(26, settings_5b_27translog_27_5d_5b_27flushThresholdPeriod_27_5d);
        setValue(27, settings_5b_27translog_27_5d_5b_27flushThresholdSize_27_5d);
        setValue(28, settings_5b_27translog_27_5d_5b_27interval_27_5d);
        setValue(29, settings_5b_27unassigned_27_5d);
        setValue(30, settings_5b_27unassigned_27_5d_5b_27nodeLeft_27_5d);
        setValue(31, settings_5b_27unassigned_27_5d_5b_27nodeLeft_27_5d_5b_27delayedTimeout_27_5d);
        setValue(32, settings_5b_27warmer_27_5d);
        setValue(33, settings_5b_27warmer_27_5d_5b_27enabled_27_5d);
        setValue(34, tableName);
    }
}
